In [217]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np 

In [280]:
X, y = make_regression(n_samples=200, n_features=4)
X = pd.DataFrame(X, columns=['f1', 'f2', 'f3', 'f4'])
y = pd.Series(y)

In [282]:
X_train, X_test, y_train, y_test = X.iloc[:150], X.iloc[150:], y.iloc[:150], y.iloc[150:]

In [246]:
class MyKNNReg: 
    def __init__(self, k=3): 
        self.k = k
        self.train_size = None

    def __repr__(self): 
        return f'MyKNNReg class: k={self.k}'

    def fit(self, X: pd.DataFrame, y: pd.Series):
        self.__X_train, self.__y_train = X.values, y.values 
        self.train_size = X.shape

    def predict(self, X: pd.DataFrame): 
        X_test = X.values
        preds = []
        for x in X_test:                                               ## проходимся по каждому объекту из тестовой выборки  
            ## расстояние для всех объектов  train
            dist = np.sqrt(np.sum((self.__X_train - x)**2, axis=1))  
            k_idx = np.argsort(dist)[:self.k]                          ## сортируем расстояние по возрасстанию (сортируются поиндексно) возращаем k элементов
            k_val = self.__y_train[k_idx]                              ## находим значения самый ближайших точек
            preds.append(np.mean(k_val))                               ## усредняем и длавляем в список preds
        return np.array(preds)
            

In [248]:
model = MyKNNReg(k=3)

In [250]:
model.fit(X_train,y_train)

In [252]:
model.predict(X_test)

array([-42.04494448,  -1.09862253, -31.29011617,   3.2890126 ,
       -19.63064566, -27.62425075,  41.94625461,  38.97094778,
       -59.43006166,  69.2671428 ,  67.58153015,  54.42428308,
       -17.97961399,  95.03060853,  32.86935372,  42.15551195,
        -6.04067111,  58.09212651,  42.8478305 , -28.82786963,
        91.42504899,  14.81551432,  23.87618913,  14.37575637,
        91.42504899, -31.25160757, -36.38303846,  22.83568211,
       -28.05742506, -33.14988035,  90.54449943,  54.00419585,
        82.36557648, -31.28565367, -61.85035233,  70.01746963,
        -1.18426036,  27.6453471 ,  37.1426021 ,  69.43015247,
        -0.25384779,  43.18428772, -11.26047679,  27.98324224,
        11.60774655,  36.46935887,  53.99376767,  99.70183217,
       -78.48639193,  50.76797637])

In [231]:
X_train.shape

(150, 4)

In [233]:
X_test.shape

(50, 4)

In [235]:
X_test.to_numpy().shape

(50, 4)

In [237]:
a = np.array([34, 2, 76, 45, 90, 43])

In [239]:
i = np.argsort(a)
i

array([1, 0, 5, 3, 2, 4], dtype=int64)

In [241]:
a[i]

array([ 2, 34, 43, 45, 76, 90])